# this document is valid
spring:
  profiles:
    active: "dev"
server:
  port: 8080
  tomcat:
    max-swallow-size: -1
---
# 운영 profile
spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    url: jdbc:mysql://192.168.55.148:3306/community?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul&tinyInt1isBit=false
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
---
# 개발 profile
spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: 832462011042-612kpdahms3qesibjr313978828a6ba2.apps.googleusercontent.com
#            clientSecret: 3lEKDUjUe7VC67okjJf4Fnil
#        provider:
#          naver:
#          kakao:
  config:
    activate:
      on-profile: "dev"
  datasource:
#    url: jdbc:mysql://49.142.51.170:3306/community?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul&tinyInt1isBit=false
    url: jdbc:mysql://192.168.0.5:3306/community?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul&tinyInt1isBit=false
    username: zidol
    password: qwer1234!@#$
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    generate-ddl: true
#    database-platform: org.hibernate.dialect.h2.Database
jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  header: Authorization
  authTime: 3600
  refreshTime: 604800
#암호화 관련 정보
crypto:
  pbszUserKey: nakdCrypt2021!@#
  pbszIV: 1234561234567890
